package util

const LOCAL_CACHE_KEY_SERVER_JOIN string = "server_join_cache_key"
const TaskConsumerTag = "task-consumer"
const CompleteTaskConsumerTag = "complete-task-consumer-tag"
const NewServerJoinTag = "server-join"
const RABBITMQ_EXCHANGE_KEY = "sondesh"
const RABBITMQ_EXCHANGE = "amq.direct"
const RABBITMQ_EXCHANGE_TYPE = "direct"
const RABBITMQ_TASK_QUEUE = "tasks"
const RABBITMQ_QUEUE_JOB_SERVER = "jobserver"
const RABBITMQ_CONSUMER_TAG = "task-consumer"
const SUPABASE_URL = "https://noezfshntxmusxzfmspw.supabase.co"
const SUPABASE_JOBDETAIL_TABLE_URL = "https://noezfshntxmusxzfmspw.supabase.co/rest/v1/"
const SUPABASE_JOBDETAIL = "JobDetail"
const SUPABASE_JOBSERVERS = "JobServers"
const SUPABASE_JOBCONFIG = "JobConfig"
const SERVER_JOIN_RABBITMQ_QUEUE = "serverjoin"
const RABBITMQ_SERVER_JOIN_EXCHANGE_KEY = "joinserversondesh"
const RABBITMQ_COMPLETE_TASK_EXCHANGE_KEY = "complete-task-sondesh"
const RABBITMQ_TASK_COMPLETE_QUEUE = "complete-tasks"
